spring:
  application:
    name: micro-13-mssc-config-server
  cloud:
    config:
      server:
        git:
          #          place where we are getting information from
          uri: https://github.com/KrzysztofKukla/micro-14-mssc-brewery-config-repo
          #          Spring Cloud Config clones repo on start up to temporally folder - takes some time on start up -
          #          less time on request, because we dont need to make a call to separate repository ( recommended to false )
          clone-on-start: true
          # Spring Cloud Config will be looking configuration inside 'application' name folder (for example in 'micro-02-mssc-beer-service' folder )
          search-paths: '{application}'

server:
  port: 8888

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        web: DEBUG
